[youtrack_servers]
tf-youtrack-server ansible_host=192.168.1.231

[linux_servers]
tf-ubuntu-server ansible_host=192.168.1.230
tf-youtrack-server ansible_host=192.168.1.231

[linux_servers:vars]
ansible_user=wizard
ansible_ssh_private_key_file=~/.ssh/proxmox
ansible_python_interpreter=/usr/bin/python3

[youtrack_servers:vars]
ansible_user=wizard
ansible_ssh_private_key_file=~/.ssh/proxmox
ansible_python_interpreter=/usr/bin/python3
